export const ADD_TO_CART = "ADD_TO_CART"
export const ADD_QUANTITY = "ADD_QUANTITY"
export const SUB_QUANTITY = "SUB_QUANTITY"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const EMPTY_CART = "EMPTY_CART"
export const UPDATE_PRICE = "UPDATE_PRICE"
export const SET_TOTAL = "SET_TOTAL"
export const SET_PERCENT = "SET_PERCENT"
