export const LOAD_AUTH_START = "LOAD_AUTH_START"
export const LOAD_AUTH_SUCCESS = "LOAD_AUTH_SUCCESS"
export const LOAD_AUTH_FALSE = "LOAD_AUTH_FALSE"

export const LOGOUT_AUTH = "LOGOUT_AUTH"
export const UPDATE_STATE_AUTH = "UPDATE_STATE_AUTH"
